"""
JWT utilities for demo user identification

Generates JWT tokens for demo users and provides verification function
for aipartnerupflow's JWT middleware.

Uses aipartnerupflow's generate_token and verify_token functions for consistency.
"""

from typing import Optional, Dict, Any
from aipartnerupflow.api.a2a.server import generate_token, verify_token
from aipartnerupflow_demo.config.settings import settings


def generate_demo_jwt_token(user_id: str, expires_in_days: int = 365) -> str:
    """
    Generate JWT token for demo user
    
    Uses aipartnerupflow's generate_token function for consistency with the library.
    
    Args:
        user_id: User ID (from browser fingerprint or cookie)
        expires_in_days: Token expiration in days (default: 365 days / 1 year)
        
    Returns:
        JWT token string
    """
    # Use configured secret key (defaults to demo key if not set)
    secret_key = settings.aipartnerupflow_jwt_secret_key or "demo-secret-key-change-in-production"
    
    algorithm = settings.aipartnerupflow_jwt_algorithm
    
    # Create payload with user_id and demo marker
    payload: Dict[str, Any] = {
        "sub": user_id,  # Subject (user_id) - standard JWT claim
        "demo": True,  # Mark as demo token
    }
    
    # Use aipartnerupflow's generate_token (uses python-jose internally)
    # It will automatically add iat and exp based on expires_in_days
    token = generate_token(payload, secret_key, algorithm, expires_in_days)
    return token


def verify_demo_jwt_token(token: str) -> Optional[Dict[str, Any]]:
    """
    Verify JWT token and return payload
    
    Uses aipartnerupflow's verify_token function for consistency with the library.
    
    This function is used as verify_token_func for aipartnerupflow's JWT middleware.
    It verifies tokens generated by SessionCookieMiddleware.
    
    Args:
        token: JWT token string
        
    Returns:
        Token payload if valid, None otherwise
    """
    secret_key = settings.aipartnerupflow_jwt_secret_key or "demo-secret-key-change-in-production"
    algorithm = settings.aipartnerupflow_jwt_algorithm
    
    # Use aipartnerupflow's verify_token (uses python-jose internally)
    # It handles all error cases and returns None on failure
    return verify_token(token, secret_key, algorithm)


def get_user_id_from_token(token: str) -> Optional[str]:
    """
    Extract user_id from JWT token without verification
    
    Useful for reading user_id from cookie before verification.
    Uses python-jose for consistency with aipartnerupflow.
    
    Args:
        token: JWT token string
        
    Returns:
        User ID if token is valid format, None otherwise
    """
    try:
        from jose import jwt as jose_jwt
        # Decode without verification to get payload
        payload = jose_jwt.decode(token, options={"verify_signature": False})
        return payload.get("sub")
    except Exception:
        return None

