"""
Custom A2A server creation with quota-aware TaskRoutes

Uses aipartnerupflow v0.6.0's task_routes_class parameter instead of monkey patching.
"""

from typing import Optional
from aipartnerupflow.api.a2a.server import create_a2a_server
from aipartnerupflow_demo.api.routes.quota_task_routes import QuotaTaskRoutes
from aipartnerupflow_demo.utils.jwt_utils import verify_demo_jwt_token
from aipartnerupflow_demo.config.settings import settings
from aipartnerupflow.core.utils.logger import get_logger

logger = get_logger(__name__)


def create_quota_a2a_server(
    verify_token_func=None,
    verify_token_secret_key: Optional[str] = None,
    verify_token_algorithm: str = "HS256",
    base_url: Optional[str] = None,
    enable_system_routes: bool = True,
    enable_docs: bool = True,
):
    """
    Create A2A server with quota-aware TaskRoutes
    
    Uses aipartnerupflow v0.6.0's task_routes_class parameter for clean extension.
    No monkey patching required.
    
    For demo environment, automatically provides JWT verification function that
    validates tokens generated by SessionCookieMiddleware.
    
    Args:
        verify_token_func: Optional JWT verification function (if None, uses demo verification)
        verify_token_secret_key: Optional JWT secret key
        verify_token_algorithm: JWT algorithm (default: HS256)
        base_url: Optional base URL
        enable_system_routes: Enable system routes (default: True)
        enable_docs: Enable API docs (default: True)
        
    Returns:
        CustomA2AStarletteApplication instance with QuotaTaskRoutes
    """
    logger.info("Creating A2A server with quota-aware TaskRoutes (using task_routes_class)")
    
    # Use demo JWT verification if no custom function provided
    # This allows SessionCookieMiddleware-generated tokens to be verified
    if verify_token_func is None:
        verify_token_func = verify_demo_jwt_token
        logger.info("Using demo JWT verification function for cookie-based tokens")
    
    # Use v0.6.0's task_routes_class parameter - no monkey patching needed!
    server = create_a2a_server(
        verify_token_func=verify_token_func,
        verify_token_secret_key=verify_token_secret_key or settings.aipartnerupflow_jwt_secret_key,
        verify_token_algorithm=verify_token_algorithm,
        base_url=base_url,
        enable_system_routes=enable_system_routes,
        enable_docs=enable_docs,
        task_routes_class=QuotaTaskRoutes,  # Direct injection
    )
    
    logger.info("Created A2A server with quota-aware TaskRoutes")
    return server

